change: Don't build esptool wheels
esptool.py version installed from the 4.9.1 wheel produces the following
error:
ModuleNotFoundError: No module named 'esptool.__init__'; 'esptool' is not a package

The issue is not present if the package is installed from tar.gz.

pytest-embedded is also broken because of this issue.

See also https://github.com/espressif/esptool/issues/1107.